const env = process.env.NODE_ENV

const defaultConfig = {
  envName: 'default', // a sanity check property for checking the loading of configs;
  env, // this is the property that should be used for environment; this and envName should match
  httpPort: 3000,
  invoices: [
    {
      status: 'unpaid',
      code: 'H3110017',
      totalAmount: 204,
      buyerName: 'STF France',
      sellerName: 'STF Belgium',
      started: '14 Feb 2018',
      blockchainAddress: '0x4E5748...c81868F6',
      info: [
        {
          infoType: 'Buyer',
          name: 'STF France',
          address: 'Des Benjoins, Rue 2, Saint-Denis',
          additionalAddress: '1202 RE, Reunion',
          code: 'STFF',
          operatingName: 'STF France',
          function: 'Local Operations, Manufacturing, Sales, Marketing',
          TRN: '004101534',
          VAT: '1265358102C54',
          IBAN: 'BE19INGB1165807110',
          BIC: 'INGBFR1B',
        },
        {
          infoType: 'Seller',
          name: 'STF Belgium',
          address: 'Rue Condorcet 163, Moe',
          additionalAddress: '1264 BE, Belgium',
          code: 'STFB',
          operatingName: 'STF Belgium',
          function: 'Local Operations, Manufacturing, Sales, Marketing',
          TRN: '190529485',
          VAT: '1101317918C49',
          IBAN: 'RE11INGB4254456990',
          BIC: 'INGBRA5C',
        },
      ],
    },
    {
      status: 'unpaid',
      code: 'H3110018',
      totalAmount: 204,
      buyerName: 'STF Spain',
      sellerName: 'STF Belgium',
      started: '07 Mar 2018',
      blockchainAddress: '0x4E5748...c81868F6',
      info: [
        {
          infoType: 'Buyer',
          name: 'STF Spain',
          address: 'Des Benjoins, Rue 2, Saint-Denis',
          additionalAddress: '1202 RE, Reunion',
          code: 'STFF',
          operatingName: 'STF Spain',
          function: 'Local Operations, Manufacturing, Sales, Marketing',
          TRN: '004101534',
          VAT: '1265358102C54',
          IBAN: 'BE19INGB1165807110',
          BIC: 'INGBFR1B',
        },
        {
          infoType: 'Seller',
          name: 'STF Belgium',
          address: 'Rue Condorcet 163, Moe',
          additionalAddress: '1264 BE, Belgium',
          code: 'STFB',
          operatingName: 'STF Belgium',
          function: 'Local Operations, Manufacturing, Sales, Marketing',
          TRN: '190529485',
          VAT: '1101317918C49',
          IBAN: 'RE11INGB4254456990',
          BIC: 'INGBRA5C',
        },
      ],
    },
    {
      status: 'unpaid',
      code: 'H3110019',
      totalAmount: 204,
      buyerName: 'STF Germany',
      sellerName: 'STF Belgium',
      started: '25 Apr 2018',
      blockchainAddress: '0x4E5748...c81868F6',
      info: [
        {
          infoType: 'Buyer',
          name: 'STF France',
          address: 'Des Benjoins, Rue 2, Saint-Denis',
          additionalAddress: '1202 RE, Reunion',
          code: 'STFF',
          operatingName: 'STF Germany',
          function: 'Local Operations, Manufacturing, Sales, Marketing',
          TRN: '004101534',
          VAT: '1265358102C54',
          IBAN: 'BE19INGB1165807110',
          BIC: 'INGBFR1B',
        },
        {
          infoType: 'Seller',
          name: 'STF Belgium',
          address: 'Rue Condorcet 163, Moe',
          additionalAddress: '1264 BE, Belgium',
          code: 'STFB',
          operatingName: 'STF Belgium',
          function: 'Local Operations, Manufacturing, Sales, Marketing',
          TRN: '190529485',
          VAT: '1101317918C49',
          IBAN: 'RE11INGB4254456990',
          BIC: 'INGBRA5C',
        },
      ],
    },
  ],
}

export default defaultConfig
